#!/usr/bin/env python3

import os
import subprocess
import re
import base64
import hashlib
import sys

TABFLOW_PREFIX = "/tmp/tabflow/"
TABFILE = "tabs"
SWITCHTO_PIPE = "switchto"
ICON_PATH = "icons/"
ROFI_ICON_STRING = "\x00icon\x1f"
URL_PATTERN = re.compile(r"(https://|http://|).*\..*(\..*)*(/.*)*")

def main():
    # Read all open tabs
    tabs = read_tabs()
    # Split up the tab info into a list
    tabs = [tab_info.split("\t") for tab_info in tabs.split("\n")]

    picker = None
    if len(sys.argv) == 2:
        picker = sys.argv[1]

    if picker:
        choices = format_tabs_generic(tabs)
        choice = execute_generic(choices, picker)
    else:
        choices, icons_enabled = format_tabs_rofi(tabs)
        choice = execute_rofi(choices, icons_enabled)

    # Exit if nothing was chosen
    if choice == "":
        return

    if not choice.isdigit():
        # If index of choice is not a tab id: open a new tab with the string as the query
        firefox_search(choice)
    else:
        # Parse the string to int, ids with leading zeros crash the host app
        id = int(choice)
        write_tab_id(id)



def read_tabs() -> str:
    try:
        f = open(TABFLOW_PREFIX + TABFILE, 'r')
    except FileNotFoundError:
        print("Could not find tab file. Exiting!")
        exit(1)
    else:
        tabs = f.read().strip()
        f.close()
        return tabs

def write_tab_id(id: int):
    try:
        pipe = open(TABFLOW_PREFIX + SWITCHTO_PIPE, "w")
    except FileNotFoundError:
        print("Could not find switchto pipe. Exiting!")
        exit(1)
    else:
        pipe.write(str(id))
        pipe.flush()
        pipe.close()

def format_tabs_rofi(tabs: list[list[str]]) -> tuple[str, bool]:
    choices = ""
    icons_enabled = False
    for tab in tabs:
        if len(tab) < 3:
            continue
        id, title, url = tab[0], tab[1], tab[2]
        icon_suffix = ""
        # There should be an icon if the array contains four elements
        if len(tab) == 4:
            icons_enabled = True
            icon, file_name = tab[3], tab[3]
            if not file_name.endswith(".ico"):
                file_name = hashlib.sha256(icon.encode()).digest().hex() + ".ico"
                if not os.path.exists(TABFLOW_PREFIX + ICON_PATH + file_name):
                    # Grab the actual favicon data from the data blob
                    favicon = base64.b64decode(icon.split(",")[1])
                    with open(TABFLOW_PREFIX + ICON_PATH + file_name, "wb") as f:
                        f.write(favicon)
            icon_suffix = ROFI_ICON_STRING + TABFLOW_PREFIX + ICON_PATH + file_name
        choices = choices + id + "\t" + title + "\t" + url + icon_suffix + "\n"
    return choices, icons_enabled

def format_tabs_generic(tabs: list[list[str]]) -> str:
    choices = ""
    for tab in tabs:
        if len(tab) < 3:
            continue
        id, title, url = tab[0], tab[1], tab[2]
        choices = choices + id + "\t" + title + "\t" + url + "\n"
    return choices


def execute_rofi(choices: str, icons: bool) -> str:
    choice = subprocess.run(
        [
        "rofi",
        "-dmenu",
        "-p", "Select Tab",
        "-i",
        "-show-icons" if icons else "",
        "-location", "0"
        ], input=choices.encode(), capture_output=True)
    choice = choice.stdout.decode()
    choice = choice.strip('\n')
    choice = choice.split('\t')
    return choice[0]

def execute_generic(choices: str, picker: str) -> str:
    choice = subprocess.run(
        [
            picker,
        ], input=choices.encode(), capture_output=True)
    choice = choice.stdout.decode()
    choice = choice.strip('\n')
    choice = choice.split('\t')
    return choice[0]

def firefox_search(choice: str):
    new_tab = f"https://duckduckgo.com/?t=ffab&q={choice}"
    if URL_PATTERN.match(choice):
        new_tab = choice
    subprocess.run([
        "firefox",
        "--new-tab",
        new_tab
    ])

if __name__ == "__main__":
    main()
