#!/usr/bin/env python3

import sys
import os
import json
import struct
from threading import Thread

TABFLOW_PREFIX = "/tmp/tabflow/"
SWITCHTO_PIPE = "switchto"
TABFILE = "tabs"
DIR_PERMISSIONS = 0o1700
PERMISSIONS = 0o600


def getMessage():
    rawLength = sys.stdin.buffer.read(4)
    if len(rawLength) == 0:
        print("Invalid message length. Exiting!", file=sys.stderr)
        exit(1)
    messageLength = struct.unpack("@I", rawLength)[0]
    message = sys.stdin.buffer.read(messageLength).decode("utf-8")
    return json.loads(message)


def encodeMessage(messageContent):
    encodedLength = struct.pack("@I", len(messageContent))
    return {'length': encodedLength, 'content': messageContent.encode("utf-8")}


def sendMessage(encodedMessage):
    sys.stdout.buffer.write(encodedMessage["length"])
    sys.stdout.buffer.write(encodedMessage["content"])
    sys.stdout.buffer.flush()


def opener(path, flags):
    return os.open(path, flags, mode=PERMISSIONS)


def readerThread():
    with open(TABFLOW_PREFIX + TABFILE, 'w', opener=opener) as f:
        while True:
            f.seek(0)
            receivedMessage = getMessage()
            f.write(receivedMessage)
            f.truncate()


def writerThread():
    try:
        if not os.path.exists(TABFLOW_PREFIX + SWITCHTO_PIPE):
            os.mkfifo(TABFLOW_PREFIX + SWITCHTO_PIPE, mode=PERMISSIONS)
    except OSError:
        print("An error occured while creating the FIFO pipe. Exiting!")
        exit(1)
    while True:
        try:
            f = open(TABFLOW_PREFIX + SWITCHTO_PIPE, 'r')
        except FileNotFoundError:
            print("Could not find pipe")
            exit(1)
        else:
            sendMessage(encodeMessage(f.read()))
            f.close()


if __name__ == "__main__":
    if not os.path.exists(TABFLOW_PREFIX):
        os.mkdir(TABFLOW_PREFIX, mode=DIR_PERMISSIONS)
    if not os.path.exists(TABFLOW_PREFIX + "icons/"):
        os.mkdir(TABFLOW_PREFIX + "icons/", mode=DIR_PERMISSIONS)
    reader = Thread(target=readerThread)
    reader.start()
    writer = Thread(target=writerThread)
    writer.start()
    reader.join()
    writer.join()
